workflowtool1/urls.py
from django.conf.urls import patterns, include, url, handler404
import request_handler.views
from django.conf import settings

from django.contrib import admin
admin.autodiscover()

# from dajaxice.core import dajaxice_autodiscover, dajaxice_config
# dajaxice_autodiscover()

handler404 = 'request_handler.views.view_404'

urlpatterns = patterns(
    '',
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT}),
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),

    # url(r'^$', request_handler.views.mainpage),
    url(r'^login/(?P<path>.*)$', request_handler.views.login_handler),
    url(r'^signup/(?P<path>.*)/$', request_handler.views.signup), 	
    url(r'^logout/(?P<path>.*)$', request_handler.views.logout_handler),


    url(r'^feedback/$', request_handler.views.feedback),
    # url(r'^subscribe/$', request_handler.views.subscribe), 

    # url(r'^dashboard/$', request_handler.views.dashboard),
    # url(r'^gallery/$', request_handler.views.gallery),

    url(r'^about/$', request_handler.views.about),


    url(r'^get_storyboard/(?P<username>.*)/(?P<order_id>\w+)$', request_handler.views.get_storyboard),



    url(r'^contact/$', request_handler.views.contact),

    url(r'^$', request_handler.views.dashboard), #comment these 2 lines while uncommenting the urls pertaining to bizmovies
    url(r'^individual_order_profile/(?P<username>\w+)/(?P<order_title>\w+)/$', request_handler.views.individual_order_profile),  #comment these 2 lines while uncommenting the urls pertaining to bizmovies 

    url(r'^enquiry_profile/(?P<username>\w+)/(?P<enquiry_title>\w+)/$', request_handler.views.enquiry_profile),

    url(r'^workflowtoolapp/$', request_handler.views.workflowtoolapp),
    url(r'^dashboard/(?P<username>\w+)/$', request_handler.views.dashboard),
    url(r'^storyboard/$', request_handler.views.storyboard_view),

    url(r'^create_enquiry/(?P<enquiry_title>\w+)/(?P<current_user>\w+)/$', request_handler.views.create_enquiry),

    url(r'^create_po/(?P<loggedin_user>\w+)/(?P<enquiry_title>\w+)/$', request_handler.views.create_po),

    # url(r'^workflowtable/video_profile/(?P<video_title>\w+)/$', request_handler.views.video_profile)

    # handler404 = 'request_handler.views.view_404',

   
)

request_handler/forms.py
from django import forms
from request_handler.models import *

class UploadTemplateForm(forms.Form):


	logo = forms.FileField(label='Select a file')

 
	description = forms.CharField(max_length=100, widget=forms.Textarea(attrs={'rows': 6}))

	description = forms.CharField(max_length=300,  widget=forms.Textarea(attrs={'rows': 4}))


	var1 = forms.FileField(label='Select a file')

	var2 = forms.FileField(label='Select a file')

	var3 = forms.FileField(label='Select a file')

	var4 = forms.FileField(label='Select a file')

	var5 = forms.FileField(label='Select a file')

	var6 = forms.FileField(label='Select a file')

	var7 = forms.FileField(label='Select a file')

	var8 = forms.FileField(label='Select a file')

	var9 = forms.FileField(label='Select a file')

	var10 = forms.FileField(label='Select a file')

	var11 = forms.FileField(label='Select a file')




class FeedbackForm(forms.Form):
    rate_types = (
        ('excellent' , 'Excellent'),
        ('very_good' , 'Very Good'),
        ('quite_good' , 'Quite Good'),
        ('somewhat_good' , 'Somewhat Good'),
        ('could_better' , 'Could have been better'),		
        ('need_improve', 'Need to improve a lot')
    )
    
    rate = forms.ChoiceField(choices=rate_types)
    message = forms.CharField(max_length=400, widget=forms.Textarea(attrs={'rows': 6}))

workflowtool1/templates/base.html
<!DOCTYPE HTML>
<html lang="en">
<head>
    <title>{% block title %}BizMovies{% endblock %}</title>

    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    

      <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
        <link href='http://fonts.googleapis.com/css?family=Carrois+Gothic' rel='stylesheet' type='text/css'>

        <link href="{{ STATIC_URL }}css/bootstrap.css" rel="stylesheet">
        
        <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/wide.css" id="layout">
        <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/style.css">
        <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/colors/default.css" id="colors">

    
    <style>
    	body{
    		margin-top:21px;
    	}
    	.modal { display:none; }
    </style>
    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    {% block custom_stylesheets %}{% endblock %}
    {% block head_js %}{% endblock %}

</head>
<body>

    {%include "login.html"%}
    {%include "signup.html"%}
	{% include "messages.html" %}
    {% include "scripts.html" %}

    {% block content %}
    {% endblock %}

    {% block footer %}
    {% endblock %}

    {% block body_js %}
    {% endblock %}
    
</body>
</html>

workflowtool1/templates/confirm_po_modal.html
<div class="modal fade" id="confirm_po_modal" tabindex="-1" style="display:none;width:600px;left:670px;top:100px;max-height:500px;top:40%;">
    <div class="modal-header">
        <button class="close" data-dismiss="modal">×</button>
        <h3>Enter The PO Number :-</h3>
    </div>
    <div class="modal-body" id="create_enquiry_modal_body" style="width:95%; max-height:500px;">

        <div class="alert alert-success" id="create_po_msg_container" style="width:400px;margin-left:230px; height:200px; display:none;">
            <h4 style="margin-left:100px;">Creating PO...</h4>
        </div>

        <div id="create_po_form_body" style="display:block;">
            <form id="create_po_form" class="well form-horizontal"
                 method="post" accept-charset="utf-8" action="/create_po/{{loggedin_user}}/{{selected_enquiry.title}}/">
                <fieldset>
                    <div class="row-fluid">
                        <div class="control-group">
                                    <div class="control-label">PO Number : </div>
                                    <div class="controls">
                                      
                                        <input name="po_no" class="span12" id="po_no_input" required type="text">

                                    </div>
                        </div>

                    </div>
                     <div class="row-fluid">
                        <div class="control-label">Scanned Image of PO (optional) : </div>
                                    <div class="controls">
                                      
                                        <input name="po_file" class="span12" id="po_scan_input" type="file">

                                    </div>
                    </div>

                <div class="row-fluid">
                    <button id="create_po_button" type"submit"
                    class="btn btn-large btn-inverse" style="width:46%;margin-left:27%;margin-top:40px;">Create</button>
                </div>

                </fieldset>

            </form>
        </div>
    </div>
</div>

workflowtool1/templates/enquiries_table.html
<table class="table table-hover" id="enquiries_table">

           <ul class="nav nav-tabs">

              <tr id="enquiry_tabs" style="display:table-row;">

                <th>sl no</th>
                <th>title</th>
                <!-- <th>story-board</th> -->
                <th>time frame</th>
                <th>Client</th>
                <th>status</th> 
                
              </tr>

            </ul>



      {%if enquiries%}

        {%for enquiry in enquiries reversed%}

    <tr>


              <td style="font-size:150%;"><a target="_blank" href="/enquiry_profile/{{current_user}}/{{enquiry.title}}">{{enquiry.id}}</a></td>

              <td style="font-size:150%;"><a target="_blank" href="/enquiry_profile/{{current_user}}/{{enquiry.title}}"><strong>{{enquiry.title}}</strong></a></td>

        <!--       <td>
                <button class="btn btn-success storyboard" onclick="storyboard_modal({{video.id}})">View</button>
              </td> -->

              <td style="font-size:150%;">{{enquiry.timeframe}}</td>

              <td style="font-size:150%;">{{enquiry.client}}</td>
              
              <td style="font-size:150%;">{{enquiry.status}} </td>
                   
    

    </tr>

      {%endfor%} 


      {%else%}

              <h5>no enquiries to display</h5>

      {%endif%} 


    </table>

workflowtool1/templates/enquiry_modal.html
<div class="modal fade" id="enquiry_modal" tabindex="-1" style="display:none;width:1050px;left:425px;max-height:700px;top:40%;">
    <div class="modal-header">
        <button class="close" data-dismiss="modal">×</button>
        <h3>Submit An Enquiry Here...</h3>
    </div>
    <div class="modal-body" id="create_enquiry_modal_body" style="width:95%; max-height:700px;">

        <div class="alert alert-success" id="create_enquiry_msg_container" style="width:99%;margin:5px;padding:5px;max-height:100px; display:none;">
            <h4 style="margin-left:100px;">Creating enquiry...</h4>
        </div>

        <div id="create_enquiry_form_body" style="display:block;">
            <form id="enquiry_form" class="well form-horizontal"
                action="" method="post" accept-charset="utf-8">
                <fieldset>
                    <div class="row-fluid">
                        <div class="span6">

                                <div class="control-group">
                                    <div class="control-label">Title</div>
                                    <div class="controls">
                                        <input id="enquiry_title" name="enquiry_title" type="text" maxlength="149" value="">
                                    </div>
                                </div>


                                <div class="control-group">
                                    <div class="control-label">Target Audience/ Users</div>
                                    <div class="controls row-fluid">
                                        <select id="enquiry_target_audience" name="enquiry_target_audience">
                                          <option value="employees">Your Employees</option>
                                          <option value="clients">Your Clients</option>
                                          <option value="internet">Internet (Everyone)</option>
                                          <option value="other">Other</option>
                                        </select>
                                    </div>
                                </div>

                                <div class="control-group">
                                    <div class="control-label">Purpose Of Video</div>
                                    <div class="controls row-fluid">
                                        <select id="enquiry_end_purpose" name="enquiry_target_audience">
                                          <option value="product_promotion">Product Promotion</option>
                                          <option value="training">Training</option>
                                          <option value="event_promotion">Event Promotion</option>
                                          <option value="topical_awareness">Topical Awareness</option>
                                          <option value="product_description">Product Description</option>
                                          <option value="other">Other</option>
                                        </select>
                                    </div>
                                </div>

                           

                                <div class="control-group">

                                    <div class="control-label">
                                        Your Requirements
                                    </div>

                                    <div class="controls row-fluid">
                                        <ul id="enquiry_requirements">
                                            <li>
                                                <div class="span12">

                                                        <select class="span4 enquiry_category" id="enquiry_category" name="enquiry_category">
                                                          <option value="animatedvideos">Animated Videos</option>
                                                          <option value="liveactionvideos">Live Action Videos</option>
                                                          <option value="elearning">Elearning Videos</option>
                                                          <option value="itap">ITAp (ELMS)</option>
                                                          <option value="others">Others</option>
                                                        </select>
                                                        <input id="enquiry_quantity_view" type="text" value="0" style="width:40px;">
                                                        <span>Units </span>

                                                        <!--                                         
                                                        <input id="enquiry_quantity_slider"type="range" step="1" min="1" max="101" value="0"  style="width:150px;">
                                                     -->                        
                                               </div>
                                            </li>
                                        </ul>

                                       <div class="span6">
                                        <span class="btn btn-mini btn-info" style="margin-left:-10px !important; margin:10px;" onclick="cln=this.parentElement.previousElementSibling.firstElementChild.cloneNode(true); console.log(this.parentElement.previousElementSibling.firstElementChild); this.parentElement.previousElementSibling.appendChild(cln);">Add More</span>
                                       </div>

                                    </div>
    

                                </div>

                        </div>

                        <div class="span5">
                                <div class="control-group">
                                    <div class="control-label">Additional Description</div>
                                    <div class="controls">
                                        <textarea rows="8" id="enquiry_description" name="enquiry_description" type="text" maxlength="2990" value=""></textarea>
                                    </div>
                                </div>
                                <div class="control-group">
                                    <div class="control-label">Approx. Timeframe (Deadline)</div>
                                    <div class="controls">
                                        <div id="enquiry_timeframe" name="enquiry_timeframe" style=""></div>
                                    </div>
                                </div>
                        </div>
                    </div>
                </fieldset>
                <div class="row-fluid">
                    <button id="create_enquiry_button" {%if not loggedin%} data-dismiss="modal" data-toggle="modal" data-target="#login-modal" {%else%} onclick="event.preventDefault();create_enquiry('{{current_user}}')" {%endif%} 
                    class="btn btn-large btn-danger" style="width:46%;margin-left:27%;margin-top:40px;">Submit</button>
                </div>
            </form>
        </div>
    </div>
</div>

workflowtool1/templates/enquiry_profile_details_table.html
<table class="table table-hover" id="selected_enquiry_details_table" style="padding:100px;margin-top:50px;">

           <ul class="nav nav-tabs">

              <tr id="selected_enquiry_details_header" style="display:table-row;">

                <th>sl no</th>
                <th>category</th>
                <!-- <th>story-board</th> -->
                <th>quantity</th>
                
              </tr>

            </ul>





    {%if selected_enquiry%}        

    <tbody id="selected_enquiry_details_body">





<!--               <td style="font-size:150%;"><a target="_blank" href="/enquiry_profile/{{current_user}}/{{enquiry.title}}">{{enquiry.id}}</a></td>

              <td style="font-size:150%;"><a target="_blank" href="/enquiry_profile/{{current_user}}/{{enquiry.title}}"><strong>{{enquiry.title}}</strong></a></td>

              <td>
                <button class="btn btn-success storyboard" onclick="storyboard_modal({{video.id}})">View</button>
              </td>

              <td style="font-size:150%;">{{enquiry.timeframe}}</td>

              <td style="font-size:150%;">{{enquiry.client}}</td>
              
              <td style="font-size:150%;">{{enquiry.status}} </td> -->
                   



    </tbody>



      {%else%}

              <h5>selected enquiry couldnt be found</h5>

      {%endif%} 


    </table>

workflowtool1/templates/messages.html
{% if messages %}
    {% for message in messages %}
    <div class="alert fade in {% if message.tags %}{{ message.tags }}{% endif %}" style="max-width: 500px; text-align: center; margin: auto; z-index: 2222; position:fixed;left:66%">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                {{ message }}
              </div>
    {% endfor %}
{% endif %}

workflowtool1/templates/nav.html
       <div id="wrapper" class="container-fluid">


            <div class="ie-dropdown-fix" >
         

                <!-- Navigation -->
                <div id="navigation">
                    <ul id="nav">

                        <li><a href="/dashboard/{{loggedin_user}}" class="active">DashBoard</a></li>

                        <li><a href="/about/">About Us</a></li>
                        
                        <!-- <li><a href="/contact/">Contact</a></li> -->
                        
                        {%if loggedin%}
                            
                                <li style="float:right">
                                  <a id="logout_link" href=""><button class="pull-right btn btn-danger" style="color:white">Logout</button></a>
                                </li>

                                <script type="text/javascript">
                                    var pathname = window.location.pathname;
                                    console.log(pathname)
                                    document.getElementById('logout_link').href = "/logout" + pathname
                                    console.log(document.getElementById('logout_link').href )
                                </script>
                            
                            
                        {% else %}

                                <li style="float:right">
                                  <a href="#"><button class="pull-right btn btn-danger" data-toggle="modal" data-target="#login-modal"  style="color:white">Login/SignUp</button></a>
                                </li>
                        {%endif%}

                    </ul>

                </div> 
                <div class="nav-shadow"></div>
                <div class="clear"></div>

            </div>

workflowtool1/templates/order_profile.html
{% extends "base.html" %}



{% block title %} Order Details {% endblock %}

{% block custom_stylesheets %}
<!--[if IE 7 ]><html class="ie ie7" lang="en"><![endif]-->
<!--[if IE 8 ]><html class="ie ie8" lang="en"><![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--><html lang="en"><!--<![endif]-->

       <link rel="stylesheet" href="{{ STATIC_URL }}css/jquery-ui.css"/>


{% endblock %}


{% block head_js %}


                 <script type="text/javascript">

// function my_js_callback(data){
//     alert(data.message);
// }

        </script>

{% endblock %}

{% block content %}

{%include "login.html"%}
{%include "signup.html"%}


{%include "storyboard_modal.html"%}


       
        {%include "nav.html"%}



            <div class="container-fluid">
              {%if loggedin%}

              <div class="row-fluid">               

                  <div class="left_and_center span6">
                    {%if order.video%}

                    <div class="video-preview">
                      <video class="video-js vjs-default-skin" 
                            controls preload="auto" width="580px" height="360px" poster="{{order.thumb.url}}"
                              data-setup="{}">
                              <source src="{{order.video.url}}" type='video/mp4'>
                      </video>
                    </div>
                    {%else%}
                      <h4 style="padding-bottom:250px;">Animation : Not Ready </h4>
                    {%endif%}

                    <div class="video-details">
                      <h3> Order No. : {{order.order_no}} </h3>
                      <button class="btn btn-warning storyboard" onclick="storyboard_modal({{order.id}})">View Story-Board</button>

                      <h2> Title : {{order.title}} </h2>
                      <h4> DateTime Created : {{order.datetime_created}} </h4>

                      <form method="post" action=".">
                        <h3>                        
                          Current Status : {{order.status}} 

                          {%if order.status != 'approved' %}
                          <button type="submit" class="badge badge-success" name="confirm_approve" value="confirm_approve">Approve!</button>
                          {%endif%}
                        </h3>
                      </form>
                     
                    </div>

                  </div>


                  <div class="right span6" style="min-width:400px;margin-left:5px;">

                    {%include "threads.html"%}

                  </div>


              </div>


 <!--                <div class="bottom-left" style="float:left; padding:10px; background-color: black; opacity: 0.6; color: white;  border-radius : 10% / 10%; margin-bottom:1%; ">

                </div> -->



                      {%else%}
                        <div style="text-align : center; margin-bottom:20%; margin-top:10%;">
                          <a href="#"><button class="btn btn-large btn-danger" data-toggle="modal" data-target="#login-modal"  style="color:white">You Need To Login To View This Page</button></a>
                        </div>
                      {%endif%}

            </div>

                   
     


        {%include "footer.html"%}
       

 

{% endblock %}

{% block body_js %}

        <script src="{{ STATIC_URL }}js/jquery.js"></script>

        <script src="{{ STATIC_URL }}js/jquery-ui.js"></script>

        <script src="{{STATIC_URL}}js/storyboard.js"></script>


          <script type="text/javascript">
        // function myFunction(evt) {
        //   var id = evt.target.id || "No ID!";
        //   console.log(id)
        //   var element = document.getElementById(id)
        //   console.log(element)
        //   var reply_input = document.createElement("input");
        //   reply_input.type = "text";
        //   reply_input.className = "reply_input"; // set the CSS class
        //   document.element.appendChild(reply_input); // put it into the DOM
        //   };
        // </script>
      



{% endblock %}

workflowtool1/templates/signup.html
<div class="modal fade" id="signup-modal">
    <div class="modal-header">
        <button class="close" data-dismiss="modal">×</button>
        <h3>Signup</h3>
    </div>
    
    <div class="modal-body">
        <form id="signup-form" class="well form-horizontal"
            action="" method="post" accept-charset="utf-8">
            <fieldset>

                <div class="control-group">
                    <div class="control-label">Username</div>
                    <div class="controls">
                        <input id="username" name="username" type="text" placeholder="any alphanumeric text" value="">
                    </div>
                </div>

                <div class="control-group">
                    <div class="control-label">Email</div>
                    <div class="controls">
                        <input id="email" name="email" type="text" value="">
                    </div>
                </div>

                <div class="control-group">
                    <div class="control-label">First Name</div>
                    <div class="controls">
                        <input id="first_name" name="first_name" type="text" value="">
                    </div>
                </div>

                <div class="control-group">
                    <div class="control-label">Last Name</div>
                    <div class="controls">
                        <input id="last_name" name="last_name" type="text" value="">
                    </div>
                </div>

                <div class="control-group">
                    <div class="control-label">Password</div>
                    <div class="controls">
                        <input id="password" name="password" type="password" value="">
                    </div>
                </div>

                <div class="control-group">
                    <div class="control-label">Verify Password</div>
                    <div class="controls">
                        <input id="verify_password" name="verify_password" type="password" value="">
                    </div>
                </div>

                <div class="control-group">
                    <div class="control-label">{{ form.keywords.label }}</div>
                    <div class="controls">
                        {{ form.keywords|safe }}
                        {% if form.keywords.errors %}
                        <ul class="errors">
                            {% for error in form.keywords.errors %}
                            <li>{{ error }}</li>
                            {% endfor %}
                        </ul>
                        {% endif %}
                    </div>
                </div>
                <div class="control-group">
                    <div class="controls">
                        <input class="btn btn-primary" id="signup_submit" type="submit" value="Sign Up"/>
                        <button class="btn" data-dismiss="modal">Cancel</button>
                    </div>
                </div>
            </fieldset>
        </form>
    </div>
</div>

<script type="text/javascript">
var pathname = window.location.pathname;
console.log(pathname)
document.getElementById('signup-form').action = "/signup" + pathname + "/"
console.log(document.getElementById('signup-form').action )
</script>

workflowtool1/templates/storyboard_modal.html
<div class="container-fluid" id="storyboard_modal" style="display:none;height:500px !important; overflow:hidden;">
	
                <div class="row-fluid" style="padding-bottom:20px;">

                    <div id="left-tool-container" class="left-tool span3" style="border:1px solid black; cursor:pointer; height:500px; overflow-y:auto;">
                        <ul id="storyboard_nav" style="padding:5px;">

                        </ul>
                    </div>



                    <div class="storyboard_canvas span9" style="border:1px solid black; min-height:500px; position:relative;">

                        <div id="storyboard_comments" style="position:absolute;z-index:999;">
                        </div>

                        <div id="storyboard_canvas" style="position:absolute; height:100%">

                        </div>

                    </div>


                </div>

</div>

workflowtool1/templates/switcher.html
  <!-- Styles Switcher -->
        <div id="style-switcher">
            <h2>Please Don't Hesitate<a href="#">Feedback</a></h2>
            <div>
                <h3><p>What from below would you choose to describe our service.</p></h3>
                <form id="feedback-form" action="/feedback/" method="post">
                    {% csrf_token %}
                <!-- <div class="layout-style">
                                    <select id="layout-switcher">
                
                                        <option>Excellent</option>
                                        <option>Very Good</option>
                                        <option>Quite Good</option>
                                        <option>Somewhat Good</option>
                                        <option>Could have been better</option>
                                        <option>Need to improve a lot</option>
                
                                    </select>
                </div>
                                
                
                                <h3><p>Leave your feedback here</p></h3>

                                <TEXTAREA NAME="feedback" ROWS=4 COLS=30 ></TEXTAREA> -->

                                {{feedbackform.as_table}}

                                <a {%if not loggedin%}data-toggle="modal" data-target="#login-modal"{% else %}href=""{%endif%}>
                                    <button id="feedback_submit" class="btn btn-info" type="submit" name="feedback">Submit</button>
                                </a>
                
                
                </form>

        </div>

<script type="text/javascript">


var metrics = [
 [ '#id_message', 'presence', 'Cannot be empty' ],
  ];
 
 var options = {
  'submitBtnSelector' : '#feedback_submit',
   'delay' : 6000,

};

$("#feedback-form").nod( metrics, options );


</script>